"""empty message

Revision ID: 0b2675327de3
Revises: 83dcb080b8a3
Create Date: 2025-07-28 09:22:45.195616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2675327de3'
down_revision = '83dcb080b8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
