"""empty message

Revision ID: 356754a1d9cf
Revises: 6f76d7053022
Create Date: 2025-07-28 08:58:14.517321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356754a1d9cf'
down_revision = '6f76d7053022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.alter_column('user_from_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.alter_column('user_from_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
