"""empty message

Revision ID: 814ea95dab9f
Revises: e27735b7876b
Create Date: 2025-07-28 08:34:43.353649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '814ea95dab9f'
down_revision = 'e27735b7876b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.String(length=120), nullable=False),
    sa.Column('user_to_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('post_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('follower')
    # ### end Alembic commands ###
