"""empty message

Revision ID: 9cdda2fe6119
Revises: 356754a1d9cf
Create Date: 2025-07-28 09:00:01.400029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdda2fe6119'
down_revision = '356754a1d9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_origin_id', sa.Integer(), nullable=False))
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('user_origin_id')

    # ### end Alembic commands ###
